DEFAULT_WIDTH = 960
DEFAULT_HEIGHT = 540
SCREEN_SIZE = DEFAULT_WIDTH, DEFAULT_HEIGHT
WINDOW_TITLE = "Jack's Sudoku"

WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
HIGHLIGHT = (255, 255, 173)
BLUE = (173, 216, 230)

GRID_SIZE = 490
CELL_SIZE = 52

'''
X, YPadding
'''

X_LFT_PAD = 18

X_RHT_PAD = X_LFT_PAD * 2 + GRID_SIZE

Y_PAD = 27

IC_PADDING = 10
INX_PADDING = 20
INY_TOP_PADDING = 41
INY_BTM_PADDING = 50

IB_PADDING = 7.5

'''
Component Dimensions
'''

GAME_BOARD_X, GAME_BOARD_Y = X_LFT_PAD, Y_PAD

DIFFICULTY_BUTTON_WIDTH = NEW_PUZZLE_BUTTON_WIDTH = 105
DIFFICULTY_BUTTON_HEIGHT = NEW_PUZZLE_BUTTON_HEIGHT = 30
DIFFICULTY_BUTTON_SIZE = NEW_PUZZLE_BUTTON_SIZE = DIFFICULTY_BUTTON_WIDTH, DIFFICULTY_BUTTON_HEIGHT
DIFFICULTY_BUTTON_X = NEW_PUZZLE_BUTTON_X = X_RHT_PAD
DIFFICULTY_BUTTON_Y = NEW_PUZZLE_BUTTON_Y = Y_PAD

CLOCK_SIZE = 420, 90
CLOCK_WIDTH, CLOCK_HEIGHT = CLOCK_SIZE
CLOCK_X, CLOCK_Y = X_RHT_PAD, DIFFICULTY_BUTTON_HEIGHT + (Y_PAD + IC_PADDING)

MODE_BUTTON_SIZE = 210, 40
MODE_BUTTON_WIDTH, MODE_BUTTON_HEIGHT = MODE_BUTTON_SIZE
MODE_BUTTON_X, MODE_BUTTON_Y = X_RHT_PAD, CLOCK_Y + CLOCK_HEIGHT + IC_PADDING

NUMBER_BOARD_SIZE = 420, 256
NUMBER_BOARD_WIDTH, NUMBER_BOARD_HEIGHT = NUMBER_BOARD_SIZE
NUMBER_BOARD_X, NUMBER_BOARD_Y = X_RHT_PAD, MODE_BUTTON_Y + MODE_BUTTON_HEIGHT + IC_PADDING

NUMBER_BUTTON_SIZE = 64, 62
NUMBER_BUTTON_WIDTH, NUMBER_BUTTON_HEIGHT = NUMBER_BUTTON_SIZE
NUMBER_BUTTON_X, NUMBER_BUTTON_Y = X_RHT_PAD + IC_PADDING, NUMBER_BOARD_Y + INY_TOP_PADDING

PUZZLE_BUTTON_SIZE = 135, 30
PUZZLE_BUTTON_WIDTH, PUZZLE_BUTTON_HEIGHT = PUZZLE_BUTTON_SIZE
PUZZLE_BUTTON_X, PUZZLE_BUTTON_Y = X_RHT_PAD, NUMBER_BOARD_Y + NUMBER_BOARD_HEIGHT + IC_PADDING






