DEFAULT_WIDTH = 960
DEFAULT_HEIGHT = 540
SCREEN_SIZE = DEFAULT_WIDTH, DEFAULT_HEIGHT
WINDOW_TITLE = "Jack's Sudoku"

WHITE = (255, 255, 255)

X_PADDING = 18
Y_PADDING = 27

'''
Component Dimensions
'''
GRID_SIZE = 486
CELL_SIZE = GRID_SIZE // 9


DIFFICULTY_BUTTON_WIDTH = NEW_PUZZLE_BUTTON_WIDTH = 105
DIFFICULTY_BUTTON_HEIGHT = NEW_PUZZLE_BUTTON_HEIGHT = 30
DIFFICULTY_BUTTON_SIZE = NEW_PUZZLE_BUTTON_SIZE = DIFFICULTY_BUTTON_WIDTH, DIFFICULTY_BUTTON_HEIGHT

CLOCK_SIZE = 420, 90
CLOCK_WIDTH, CLOCK_HEIGHT = CLOCK_SIZE

MODE_BUTTON_SIZE = 210, 40
MODE_BUTTON_WIDTH, MODE_BUTTON_HEIGHT = MODE_BUTTON_SIZE

NUMBER_BOARD_SIZE = 420, 256
NUMBER_BOARD_WIDTH, NUMBER_BOARD_HEIGHT = NUMBER_BOARD_SIZE

NUMBER_BUTTON_SIZE = 64, 62
NUMBER_BUTTON_WIDTH, NUMBER_BUTTON_HEIGHT = NUMBER_BUTTON_SIZE

PUZZLE_BUTTON_SIZE = 135, 30
PUZZLE_BUTTON_WIDTH, PUZZLE_BUTTON_HEIGHT = PUZZLE_BUTTON_SIZE
